### ISSUE TITLE
calculate remaining elevation returns "noTrk"

### ISSUE THREAD

**Issue by emariu** [Falcosc/locus-addon-tasker#1]
Hello Falco,
do you have new version ready with all examples ready and working?

**Comment by Falcosc** [comment]
Newer version with braking changes is ready and untestet, but all existing tasker projekts have to be reconfigured because the current version doesn't use the correct tasker api.

After I did test it by my self it will be deliverd to everyone.

**Comment by emariu** [comment]
Great news.I'll be waiting for you to test and post also all the new tasker tasks you had told me about

Thanks,Marius 

    On Thursday, November 1, 2018 11:11 AM, Falcosc <notifications@github.com> wrote:
 

 Newer version with braking changes is ready and untestet, but all existing tasker projekts have to be reconfigured because the current version doesn't use the correct tasker api.After I did test it by my self it will be deliverd to everyone.—

**Comment by Falcosc** [comment]
The new version is online. I did implement automatic navigation track selection and did remove manual track selection. 

And I did mention planed examples.
https://github.com/Falcosc/locus-addon-tasker/wiki/Examples

Do you still need screenshots how to import Tasker configurations?

**Comment by emariu** [comment]
Hello,I did import again the scene and the profile, but now after opening dashboard and I am in a navigation in locus...  the overlay is saying no TRK what am I doing wrong? there is a navigation track 

    On Wednesday, November 7, 2018 9:34 AM, Falcosc <notifications@github.com> wrote:
 

 The new version is online. I did implement automatic navigation track selection and did remove manual track selection.And I did mention planed examples.
https://github.com/Falcosc/locus-addon-tasker/wiki/ExamplesDo you still need screenshots how to import Tasker configurations?—

**Comment by Falcosc** [comment]
A Navigation track is an overlay over your GPS Track, which got automatically created after you start 
- guiding to target
- track to target 
- or navigate to target

I did figure out that Locus Map Free doen't create a navigation track which means 2 problems:
# the dashboard can't automatically find your track, you need to manually tell the plugin which track was selected
# I did just remove this manual selection feature because you don't need it with locus pro because locus pro creates an invisible navigation track with track id "00000001" which means I have to get the deleted feature back and I need to extent the "look for track 0000001" logic with an exception for locus map free users
# the missing naviation track does reduce the elevation accuracy. For example if your track does only have 50 points the naviagion track on top of your track generates a track with maybe 200 points to get more consistent statistics.

Heare an screenshot where I tap on the track during guiding, locus shows me my track and the navigation overlay.

![screenshot_20181109-075949](https://user-images.githubusercontent.com/8665625/48250621-3929b380-e3ff-11e8-915a-0d7c36b806ac.png)

**Comment by emariu** [comment]
I have Locus pro , not free 

    On Friday, November 9, 2018 10:28 AM, Falcosc <notifications@github.com> wrote:
 

 @emariu do you have locus map free?
I do think about disabling remainig track calculation for locus free users because the manual track selection would confuse locus map pro users.
Well, I don't even know which functions are available on free because I can't test with locus free because only with locus pro you have GPS simulation features to test things :(—

**Comment by Falcosc** [comment]
You can even see that there are 2 tracks on top of each other, because of different track point count the errors are missaligned and you can acutally see that locus pro creates a track over the track:

![2018-11-09 09_37_33](https://user-images.githubusercontent.com/8665625/48251893-7132f580-e403-11e8-87ca-ba7cdc8f0e2d.png)

**Comment by emariu** [comment]
how can I debug the profile imported in tasker on my phone?I tried also with guide on to a target and the same happened No TrkAnd I do not see the second track generated on top of my go to track, just one  

    On Friday, November 9, 2018 10:40 AM, Falcosc <notifications@github.com> wrote:
 

 You can even see that there are 2 tracks on top of each other, because of different track point count the errors are missaligned and you can acutally see that locus pro creates a track over the track:—

**Comment by Falcosc** [comment]
You can manually execute the tasker task, but the NoTrack error tells you that the addon can't find the "Navigation" track.
Which makes sense if you can't find it either on your locus ui.

Please could you make a screenshot before you tap on the track line and a screenshot after you did touches on the track line?
Do short touches.

Maybe I could see how you did get a working navigation on "my track" without "navigation" track.

**Comment by emariu** [comment]
What I observed is.. if I click on any recorded track(or imported track) then it is selected and the pop-up with normal information appears(see last picture) , but if I do a normal navigate to.. a target  then if I try to clickon the navigation track.. then it is not selected and this menu is appearing..(see in ther first 2-3 pictures) 

    On Friday, November 9, 2018 11:29 AM, Falcosc <notifications@github.com> wrote:
 

 You can manually execute the tasker task, but the NoTrack error tells you that the addon can't find the "Navigation" track.
Which makes sense if you can't find it either on your locus ui.Please could you make a screenshot before you tap on the track line and a screenshot after you did touches on the track line?
Do short touches.Maybe I could see how you did get a working navigation on "my track" without "navigation" track.—

**Comment by emariu** [comment]
![screenshot_20181109-113620](https://user-images.githubusercontent.com/44325246/48255827-764d7000-e416-11e8-9c85-bf909f94c71d.png)
![screenshot_20181109-113637](https://user-images.githubusercontent.com/44325246/48255833-7baaba80-e416-11e8-83a1-e538b15331df.png)
![screenshot_20181109-113736](https://user-images.githubusercontent.com/44325246/48255837-7f3e4180-e416-11e8-8b2e-7cbd36ae1804.png)
![screenshot_20181109-113836](https://user-images.githubusercontent.com/44325246/48255841-849b8c00-e416-11e8-927a-e1c30aced2d4.jpg)

**Comment by Falcosc** [comment]
Thank you, I found one missing usecase

"Navigation without GPX file" does work on my device like you did told me.
Maybe I could implement this automatically.

**Comment by emariu** [comment]
OK please do that..

**Comment by Falcosc** [comment]
OK, I have to add manual track selection.

"Navigation with GPX Track" is available as 10000001 (constant value, usable for automation
"Navigation without GPX" is available as "87" if you have 86 tracks in database and api don't tell me that you do follow 87 or 86 ore any other track, which means you have manually select :(
"

**Comment by emariu** [comment]
I think you should do both.. First implement manual selection and in the mean time talk to Menion to update API :) 
    On Friday, November 9, 2018, 1:27:45 PM GMT+2, Falcosc <notifications@github.com> wrote:  
 
 
@emariu
Would it be ok for you to manuall select it or should I ask for an API update and wait for response?

Manual Track selection work like this:
   
   - click track line
   - click information
   - click the share icon
   - select a new menu entry "set track as active"

**Comment by Falcosc** [comment]
@emariu please try it:
https://play.google.com/apps/testing/falcosc.locus.addon.tasker 

does work well for me.

If you got noTrk or offTrk results you need to manually select the correct track
1. click navigation track line
2. click information
3. click the share icon
4. select a new menu entry "set to active"

**Comment by Falcosc** [comment]
@emariu here it is: http://help.locusmap.eu/topic/add-guiding-track-id-to-api

**Comment by emariu** [comment]
Hello.. tried again and also I had No Trk ..so I manually selected the track and then finally I got result remaining altitude :)  
The problem is that next time I use Locus and try a new navigation to another point..  I did not manually select the new track and it automatically showed the last elevation remaining to the last target(old value)
If I manually select the new track again, then the overlay is showing the same OLD value not the new one
I clicked on the overlay to make it disappear and selected again the new track and after 2 minuters the new overlay had the correct value

**Comment by emariu** [comment]
as a mention, your add-on got automatically updated on my phone from google play an hour ago.. I hope it is the latest version?!
Please make the version numbers visible when I open your add-on application from my phone, to check if it is correct version

**Comment by Falcosc** [comment]
You should trigger a recalculation on your dashboard button because the example profile is executed every 2 minutes. Or generate an app icon for manual recalculation.

Do you have hardware buttons to spare? For example I have a camera button with half press. I use half press to switch display brightness low/middle/max and full press does change between dashboard and map. I do call the overlay update on each full press and get new calculation everytime I switch to dashboard.

Or make a Task "display remaining elevation", convert it to app and add the converted app to your locus panel, like this: https://github.com/Falcosc/locus-addon-tasker/wiki/Custom-Task-Icon-at-Locus-Panel

Version number should be part of Play store or app info screen (long click on app icon if your launcher does support it)

Automatic track selection does only work during guiding or navigation based on existing track.

Do you understand why the switch from old navigation to new navigation doesn't work with your setup? The addon does have all the needed data you just need to collect it with tasker.

And did you understand when the navigation track could get automatically selected and when you get a noTrk error?

It's a little bit difficult to allign the overlay because you only have move left and move up in the "show scene" action of the task.

**Comment by Falcosc** [comment]
And thank you for testing with your device, too. I did move the beta version to release now. Don't be affraid to stay on beta track, I do actually test my app before beta phase.

**Comment by emariu** [comment]
I see now that I'm on version 1.0.3
What program do you use to map a hardware button to changing between dashboard and map? Teach me how to do it,please.
Also I need some help with setting up the scene overlay. What settings do you have? I have 1000x350 geometry,but the overlay and numbers are too big and taking much space of the map display

**Comment by Falcosc** [comment]
You can change the overlay settings in screen tab. But positioning have to be done in task.
Scene design belongs to scene config and positioniing is part of task "show scene".

I use "Autoinput" Locus Plugin to assign any hardware button id which is available on my phone. If you don't know the name of the button you can manually enter the button by pressing it in the autoinput key select dialog.

Toggle Dialog is a little bit more complicated. You have to create a locus settings preset with dashboard and a settings profile without dashboard.
Then you can create a task which select dashboard preset or non dashboard preset.
Locus Tasker Plugin "Execute Action" could then do the "Set Preset" Action to apply it.

I can't export locus presets, which means you have to create them by your own.
Maybe I do share some screenshots about this topic because I'm a little bit proud of all my hardware button tasks for brightness and dashboard management.
