### ISSUE TITLE
Guidance - target

### ISSUE THREAD

**Issue by sik0vny** [Falcosc/locus-addon-tasker#10]
Hi. I'm really missing these:
Guidance:
1. Distance to target
2. Time to target
3. Time of arrival
4. Time to next waypoint

Please, may you add them? Wihout them the whole application does not have a sense for me.

**Comment by Falcosc** [comment]
No problem, thanks for asking. You are the first who is missing these.

I'm pretty sure you are looking for these values: https://github.com/asamm/locus-api/blob/master/locus-api-android/src/main/java/locus/api/android/features/periodicUpdates/UpdateContainerGuideTrack.kt

Do you need anything else from these fields? I will map as much as possible.

I'm glad that I did not bother to implement these fields last winter because they got restructured just after implementing the updateContainer structure:

## [0.3.9] - 2019-03-18
### Added
- `UpdateContainerGuidePoint` and `UpdateContainerGuideTrack` containers in `UpdateContainer`
- extra metadata for `NavPoint` in `UpdateContainerGuideTrack`

**Comment by sik0vny** [comment]
Thank you. I think all of these might be useful. When they might be released?

**Comment by Falcosc** [comment]
To be honest, I did plan it for December but did not announce it. But end of year business did not leave any room for my hobby time projects.

It will be available at February!
After this public announcement I can't back off and need to hold my promise ;)

Could you share for which idea do you need these values? I'm just interested.

**Comment by Falcosc** [comment]
I did not test it, but it is available as beta:
https://play.google.com/apps/testing/falcosc.locus.addon.tasker

Please let me know if it needs more testing or if it is ready to publish.
